from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import os
from github_manager import GitHubManager
from ai_fixer import AIFixer
from dotenv import load_dotenv
import logging

# Load environment variables
load_dotenv()

# Initialize the logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="AI Auto-PR Bot Backend")

# Restrict CORS middleware to only allow specific origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "https://example.com"],
    allow_credentials=False,
    allow_methods=["POST"],
    allow_headers=["Content-Type", "Authorization"],
)

from typing import Optional

class FixRequest(BaseModel):
    """Request model for the /api/fix-bug endpoint"""
    github_token: Optional[str] = None
    groq_api_key: Optional[str] = None
    repo_url: str
    file_path: Optional[str] = None
    branch: str = "main"
    issue_desc: Optional[str] = None

@app.post("/api/fix-bug")
async def fix_bug(req: FixRequest) -> dict:
    """Create a pull request with a fixed bug in a GitHub repository"""
    try:
        # Fallback to environment variables if not provided
        gh_token = req.github_token
        if not gh_token or gh_token.strip() == "":
            gh_token = os.getenv("GITHUB_TOKEN")
            
        groq_key = req.groq_api_key
        if not groq_key or groq_key.strip() == "":
            groq_key = os.getenv("GROQ_API_KEY")
            
        if not gh_token:
            raise HTTPException(status_code=400, detail="GitHub Token is missing. Provide it in the request or set GITHUB_TOKEN environment variable.")
        if not groq_key:
            raise HTTPException(status_code=400, detail="Groq API Key is missing. Provide it in the request or set GROQ_API_KEY environment variable.")

        gh_manager = GitHubManager(gh_token)
        ai_fixer = AIFixer(groq_key)

        # Fetch Repo
        repo = gh_manager.get_repo(req.repo_url)
        
        # Auto-discover file if not provided
        target_file = req.file_path
        if not target_file or target_file.strip() == "":
            target_file = gh_manager.discover_main_file(repo, req.branch)
            
        # Get Original Code
        original_code, file_sha = gh_manager.get_file_content(repo, target_file, req.branch)

        # Process: Autonomous or Guided
        if req.issue_desc and req.issue_desc.strip() != "":
            fixed_code = ai_fixer.fix_code(original_code, req.issue_desc)
            pr_details = ai_fixer.generate_pr_details(original_code, fixed_code, req.issue_desc)
            explanation = req.issue_desc
        else:
            analysis = ai_fixer.analyze_and_fix(original_code)
            fixed_code = analysis["fixed_code"]
            pr_details = {
                "title": analysis["pr_title"],
                "body": analysis["pr_body"]
            }
            explanation = analysis["explanation"]

        # Create PR
        commit_msg = f"Fix: {pr_details['title']}"
        pr_url = gh_manager.create_pr_with_fix(
            repo=repo,
            file_path=target_file,
            new_content=fixed_code,
            commit_message=commit_msg,
            pr_title=pr_details['title'],
            pr_body=pr_details['body'] + "\n\n_Generated by AI Auto-PR Bot (Cosmos Edition)_",
            source_branch=req.branch
        )

        return {
            "status": "success",
            "file_path": target_file,
            "explanation": explanation,
            "original_code": original_code,
            "fixed_code": fixed_code,
            "pr_url": pr_url
        }

    except HTTPException as e:
        logger.error(f"HTTP Exception: {e}")
        raise e
    except Exception as e:
        logger.error(f"Unexpected Exception: {e}")
        raise HTTPException(status_code=500, detail="Internal Server Error")