from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import os
from github_manager import GitHubManager
from ai_fixer import AIFixer

app = FastAPI(title="AI Auto-PR Bot Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class FixRequest(BaseModel):
    github_token: str
    groq_api_key: str
    repo_url: str
    file_path: str
    branch: str = "main"
    issue_desc: str

@app.post("/api/fix-bug")
async def fix_bug(req: FixRequest):
    try:
        gh_manager = GitHubManager(req.github_token)
        ai_fixer = AIFixer(req.groq_api_key)

        # Fetch Repo & Original Code
        repo = gh_manager.get_repo(req.repo_url)
        original_code, file_sha = gh_manager.get_file_content(repo, req.file_path, req.branch)

        # AI Fix & PR Generation
        fixed_code = ai_fixer.fix_code(original_code, req.issue_desc)
        pr_details = ai_fixer.generate_pr_details(original_code, fixed_code, req.issue_desc)

        # Create PR
        commit_msg = f"Fix: {pr_details['title']}"
        pr_url = gh_manager.create_pr_with_fix(
            repo=repo,
            file_path=req.file_path,
            new_content=fixed_code,
            commit_message=commit_msg,
            pr_title=pr_details['title'],
            pr_body=pr_details['body'] + "\n\n_Generated by AI Auto-PR Bot_",
            source_branch=req.branch
        )

        return {
            "status": "success",
            "original_code": original_code,
            "fixed_code": fixed_code,
            "pr_url": pr_url
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
