from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import os
from github_manager import GitHubManager
from ai_fixer import AIFixer
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="AI Auto-PR Bot Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class FixRequest(BaseModel):
    github_token: Optional[str] = None
    groq_api_key: Optional[str] = None
    repo_url: str
    file_path: str
    branch: str = "main"
    issue_desc: str

@app.post("/api/fix-bug")
async def fix_bug(req: FixRequest):
    try:
        # Fallback to environment variables if not provided
        gh_token = req.github_token
        if not gh_token or gh_token.strip() == "":
            gh_token = os.getenv("GITHUB_TOKEN")
            
        groq_key = req.groq_api_key
        if not groq_key or groq_key.strip() == "":
            groq_key = os.getenv("GROQ_API_KEY")
            
        if not gh_token:
            raise HTTPException(status_code=400, detail="GitHub Token is missing. Provide it in the request or set GITHUB_TOKEN environment variable.")
        if not groq_key:
            raise HTTPException(status_code=400, detail="Groq API Key is missing. Provide it in the request or set GROQ_API_KEY environment variable.")

        gh_manager = GitHubManager(gh_token)
        ai_fixer = AIFixer(groq_key)

        # Fetch Repo & Original Code
        repo = gh_manager.get_repo(req.repo_url)
        original_code, file_sha = gh_manager.get_file_content(repo, req.file_path, req.branch)

        # AI Fix & PR Generation
        fixed_code = ai_fixer.fix_code(original_code, req.issue_desc)
        pr_details = ai_fixer.generate_pr_details(original_code, fixed_code, req.issue_desc)

        # Create PR
        commit_msg = f"Fix: {pr_details['title']}"
        pr_url = gh_manager.create_pr_with_fix(
            repo=repo,
            file_path=req.file_path,
            new_content=fixed_code,
            commit_message=commit_msg,
            pr_title=pr_details['title'],
            pr_body=pr_details['body'] + "\n\n_Generated by AI Auto-PR Bot_",
            source_branch=req.branch
        )

        return {
            "status": "success",
            "original_code": original_code,
            "fixed_code": fixed_code,
            "pr_url": pr_url
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
